name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build binaries
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        mkdir -p dist
        OUTPUT="dist/chartherd-${{ matrix.os }}-${{ matrix.arch }}"
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          OUTPUT="$OUTPUT.exe"
        fi
        go build -ldflags '-w -s' -trimpath -o $OUTPUT ./cmd/chartherd

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/

  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-arch container images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/chartherd:${{ github.ref_name }}
          ghcr.io/${{ github.repository_owner }}/chartherd:latest

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-binaries, build-and-push-container]
    steps:
    - name: Download binaries artifact
      uses: actions/download-artifact@v4
      with:
        pattern: binaries-*
        path: dist/
        merge-multiple: true

    - name: Create GitHub Release
      id: create-release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/chartherd-*


